### ISSUE TITLE
increment counter

### ISSUE THREAD

**Issue by sanil011** [adarsh-gupta101/DataStructures-Algorithms-in-JavaScript-TypeScript#21]
##description
#I want to add an increment counter , which can be take inspiration and  used by anyone for their project.

Please assign me this
https://user-images.githubusercontent.com/105095685/194806531-932a6a62-fd5f-4154-aa9e-cd75d3783012.mov

**Comment by adarsh-gupta101** [comment]
I guess that does not fit to this repo
