### ISSUE TITLE
 Don't you think there should be separate main folders one for javascript and one for typescript

### ISSUE THREAD

**Issue by NAJIB-B** [adarsh-gupta101/DataStructures-Algorithms-in-JavaScript-TypeScript#6]
All the folders contain only javascript files so were exactly do we add typescript files

**Comment by NAJIB-B** [comment]
Yes I would love to so for every JavaScript problem i will also give the
typescript equivalent

**Comment by adarsh-gupta101** [comment]
Great, you can start working on this🚀

**Comment by NAJIB-B** [comment]
Okay thank you🤝
